### ISSUE TITLE
--index-url works but --extra-index-url does not

### ISSUE THREAD

**Issue by bulak** [ceddlyburge/python-package-server#1]
Hello, when I in a fresh virtual env try:

    pip --verbose install python-world --extra-index-url https://ceddlyburge.github.io/python-package-server/

`pip` looks only into pypi.org/simple and throws a 404 Client Error before looking into the extra index to find your package.
If I use instead:

    pip --verbose install python-world --index-url https://ceddlyburge.github.io/python-package-server/

It works as expected. I wonder if you have a different configuration that somehow makes `pip` ignore the 404 and forces to look into the extra-urls?
I am using pip 18.1. Thanks.

**Comment by bulak** [comment]
Never mind. The issue was with pip 18.1. When upgraded to 19.1, it is gone. Thanks.

**Comment by ceddlyburge** [comment]
If only all support was this easy :)

Thanks for figuring it out ...
