### ISSUE TITLE
Is the resolution of version ranges supported?

### ISSUE THREAD

**Issue by Elijas** [ceddlyburge/python-package-server#3]
I have a requirements.txt file with the following contents:
```
my_custom_package>=1.0.0,<2.0.0
my_other_package>=1.18.0,<1.20.0
```
Will the version ranges be resolved, or is it necessary to use a PyPI server to handle the version resolution?

**Comment by ceddlyburge** [comment]
Hi Elijas

Yes, this should work fine, it is pip that does the dependency resolution. As long as your PyPi server contains all the versions that you want, then PyPi will be able to find them and work out what to do based on the requirements.txt

https://pip.pypa.io/en/stable/topics/dependency-resolution/

Cheers, Cedd

**Comment by ceddlyburge** [comment]
Hi elijas, I'm closing this issue now, I hope the explanation made sense!

**Comment by Elijas** [comment]
Thanks!
